### ISSUE TITLE
Hardware revision request: Improved power efficiency

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_MicroMod_Main_Board_Single#1]
Hi @edspark,

I'm a big fan of MicroMod products and use them extensively in my [research](https://github.com/adamgarbo/Cryologger_Glacier_Velocity_Measurement_System).

Unfortunately, one of the major drawbacks with many of the MicroMod products has been poor power efficiency (e.g., https://github.com/sparkfun/MicroMod_Data_Logging_Carrier/issues/3, https://github.com/sparkfun/MicroMod_Artemis_Processor/issues/5)

The new Main Board are exciting products. However, it would have really been nice if some of the design improvements identified in previous MicroMod products were addressed in these new designs. For example: adding a jumper pad added to the voltage divider (i.e., https://github.com/sparkfun/MicroMod_Data_Logging_Carrier/issues/1), or adding a P-MOSFET or extra regulator to control power to the microSD card. 

Low-power data logging is an extremely desirable feature for end-users. While I don't anticipate a hardware revision of the Main Boards, my hope is that low-power operation can be given more consideration in future MicroMod designs. 

Cheers,
Adam

**Comment by edspark** [comment]
These are both excellent suggestions. I've added them to my notes for future revisions, thank you @adamgarbo.
